#pragma once

#include <string_view>

#include "settings/AppSettings.h"

namespace finderx::ui {

enum class StringId {
    NewFolder,
    NewFile,
    Sort,
    Settings,
    OpenPowerShellHere,
    Search,
    FinderXSettings,
    SettingsSubtitle,
    Appearance,
    Startup,
    Files,
    Shortcuts,
    Toolbar,
    ContextMenu,
    About,
    Version,
    AppDescription,
    FontFamily,
    FontSize,
    ContextMenuFont,
    TextSize,
    MenuTextSize,
    IconSize,
    ItemPadding,
    Theme,
    Language,
    Chinese,
    English,
    Light,
    Dark,
    WindowStartup,
    FileBrowsing,
    WindowWidth,
    WindowHeight,
    Width,
    Height,
    RememberWindowSize,
    StartupFolder,
    UseCurrentFolder,
    UseCurrent,
    FileBehavior,
    ShowHiddenAndSystem,
    Favorites,
    FavoritesDescription,
    FavoriteName,
    DisplayName,
    TargetPath,
    Keyboard,
    AvailableActions,
    ToolbarOrder,
    Add,
    Remove,
    MoveUp,
    MoveDown,
    Up,
    Down,
    Ok,
    Cancel,
    MenuLabel,
    ProgramPath,
    Browse,
    Arguments,
    ShowForFiles,
    ShowForFolders,
    VsCode,
    Update,
    ChooseProgram,
    CreateShortcut,
    OpenInVsCode,
    Open,
    Rename,
    Copy,
    Cut,
    Paste,
    MoveToTrash,
    CompressZip,
    ExtractHere,
    OpenInNewTab,
    AddToFavorites,
    RemoveFromFavorites,
    RevealInExplorer,
    CopyPath,
    Refresh,
    CannotOpenPowerShell,
    CannotOpenFolder,
    CannotOpenFile,
    CannotRefreshFolder,
    CannotShowInExplorer,
    CannotCopyPath,
    CannotOpenExternalTool,
};

std::wstring_view tr(StringId id, LanguageMode languageMode);
std::wstring_view tr(StringId id);

} // namespace finderx::ui
